/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DetailMovieIdRouteImport } from './routes/detail.$movieId'
import { Route as SeatsMovieIdDateTimeRouteImport } from './routes/seats.$movieId.$date.$time'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailMovieIdRoute = DetailMovieIdRouteImport.update({
  id: '/detail/$movieId',
  path: '/detail/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsMovieIdDateTimeRoute = SeatsMovieIdDateTimeRouteImport.update({
  id: '/seats/$movieId/$date/$time',
  path: '/seats/$movieId/$date/$time',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/detail/$movieId': typeof DetailMovieIdRoute
  '/seats/$movieId/$date/$time': typeof SeatsMovieIdDateTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/detail/$movieId': typeof DetailMovieIdRoute
  '/seats/$movieId/$date/$time': typeof SeatsMovieIdDateTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/detail/$movieId': typeof DetailMovieIdRoute
  '/seats/$movieId/$date/$time': typeof SeatsMovieIdDateTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/detail/$movieId' | '/seats/$movieId/$date/$time'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/detail/$movieId' | '/seats/$movieId/$date/$time'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/detail/$movieId'
    | '/seats/$movieId/$date/$time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DetailMovieIdRoute: typeof DetailMovieIdRoute
  SeatsMovieIdDateTimeRoute: typeof SeatsMovieIdDateTimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$movieId': {
      id: '/detail/$movieId'
      path: '/detail/$movieId'
      fullPath: '/detail/$movieId'
      preLoaderRoute: typeof DetailMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats/$movieId/$date/$time': {
      id: '/seats/$movieId/$date/$time'
      path: '/seats/$movieId/$date/$time'
      fullPath: '/seats/$movieId/$date/$time'
      preLoaderRoute: typeof SeatsMovieIdDateTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DetailMovieIdRoute: DetailMovieIdRoute,
  SeatsMovieIdDateTimeRoute: SeatsMovieIdDateTimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
